"""Seed data for LEGACY app — mentors, vault resources, careers, events, reviews."""

SEED_MENTORS = [
    # ---- Business / Academics ----
    {
        "mentor_id": "mnt_ananya", "name": "Ananya Jain",
        "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "School Commerce Topper • Business Conclave Winner",
        "verified": True,
        "achievements": ["School Topper", "Business Conclave Winner", "Debate Finalist"],
        "subjects": ["Business Studies", "Economics", "Accountancy"],
        "categories": ["business", "academics", "debate"],
        "bio": "Passionate about business and finance. I love helping students build confidence and excel in competitions. I've won 4 national business conclaves and mentored 120+ juniors.",
        "rating": 4.9, "reviews_count": 126, "sessions": 128, "price": 299,
        "grade_taught": "Grade 9-12", "years": 2, "languages": ["English", "Hindi"],
        "available_slots": ["09:00", "10:00", "16:00", "17:00", "18:00"],
    },
    {
        "mentor_id": "mnt_arjun", "name": "Arjun Mehta",
        "avatar": "https://images.unsplash.com/photo-1544168190-79c17527004f?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1531545514256-b1400bc00f31?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "MUN Chair • Harvard Model UN Finalist",
        "verified": True,
        "achievements": ["Best Delegate x3", "HMUN Finalist", "Debate Captain"],
        "subjects": ["Political Science", "History", "Public Speaking"],
        "categories": ["mun", "debate", "public_speaking"],
        "bio": "MUN veteran with 15+ awards. I'll teach you how to research, negotiate, and dominate the committee floor.",
        "rating": 4.8, "reviews_count": 89, "sessions": 94, "price": 349,
        "grade_taught": "Grade 8-12", "years": 3, "languages": ["English"],
        "available_slots": ["10:00", "11:00", "17:00", "18:00", "19:00"],
    },
    {
        "mentor_id": "mnt_riya", "name": "Riya Gupta",
        "avatar": "https://images.unsplash.com/photo-1618355776464-8666794d2520?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1698434156107-17486c312c50?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "IIT Bombay CS • Coding Olympiad Gold",
        "verified": True,
        "achievements": ["IIT-B CSE", "IOI Bronze", "Google Code Jam"],
        "subjects": ["Python", "DSA", "Web Development"],
        "categories": ["coding", "ai", "academics"],
        "bio": "Full-stack developer & competitive programmer. Cracked JEE Advanced AIR 412. Let's build something amazing together.",
        "rating": 5.0, "reviews_count": 214, "sessions": 231, "price": 449,
        "grade_taught": "Grade 6-12", "years": 2, "languages": ["English", "Hindi"],
        "available_slots": ["16:00", "17:00", "18:00", "19:00", "20:00"],
    },
    {
        "mentor_id": "mnt_kabir", "name": "Kabir Rao",
        "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "Startup Founder • Shark Tank India Pitch Finalist",
        "verified": True,
        "achievements": ["Founder @18", "Shark Tank Finalist", "TIE Youth Winner"],
        "subjects": ["Entrepreneurship", "Product", "Pitching"],
        "categories": ["entrepreneurship", "business"],
        "bio": "Built a D2C brand in Class 12. I'll help you validate ideas, build MVPs, and pitch like a pro.",
        "rating": 4.9, "reviews_count": 67, "sessions": 72, "price": 499,
        "grade_taught": "Grade 9-12", "years": 1, "languages": ["English", "Hindi"],
        "available_slots": ["18:00", "19:00", "20:00"],
    },
    {
        "mentor_id": "mnt_meera", "name": "Meera Iyer",
        "avatar": "https://images.unsplash.com/photo-1580489944761-15a19d654956?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1509909756405-be0199881695?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "NID Ahmedabad • Design Thinking Coach",
        "verified": True,
        "achievements": ["NID Selected", "Adobe Design Winner"],
        "subjects": ["UI/UX", "Illustration", "Design Thinking"],
        "categories": ["design", "content"],
        "bio": "Cracked NID entrance in one attempt. I share the design portfolio & thinking process seniors wish they had.",
        "rating": 4.8, "reviews_count": 51, "sessions": 58, "price": 379,
        "grade_taught": "Grade 8-12", "years": 2, "languages": ["English", "Tamil"],
        "available_slots": ["11:00", "12:00", "17:00", "18:00"],
    },
    {
        "mentor_id": "mnt_advait", "name": "Advait Sharma",
        "avatar": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "IMO Silver • Class XII Board Topper",
        "verified": True,
        "achievements": ["IMO Silver", "Board Topper 99.2%", "KVPY Fellow"],
        "subjects": ["Mathematics", "Physics", "JEE Prep"],
        "categories": ["academics", "olympiads"],
        "bio": "Cracked JEE Advanced AIR 89. Let's demystify calculus and physics from first principles.",
        "rating": 4.9, "reviews_count": 178, "sessions": 190, "price": 399,
        "grade_taught": "Grade 9-12", "years": 2, "languages": ["English", "Hindi"],
        "available_slots": ["17:00", "18:00", "19:00", "20:00"],
    },
    # ---- Photography ----
    {
        "mentor_id": "mnt_zara", "name": "Zara Kapoor",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "NatGeo Young Photographer • Street Photography",
        "verified": True,
        "achievements": ["NatGeo Young Winner", "State Photo Award", "Published in RSTV"],
        "subjects": ["Composition", "Editing", "Storytelling"],
        "categories": ["photography", "content"],
        "bio": "Photography changed my life at 14. Let me teach you the craft of seeing — lens, light, and story.",
        "rating": 4.9, "reviews_count": 74, "sessions": 82, "price": 329,
        "grade_taught": "Grade 6-12", "years": 3, "languages": ["English", "Hindi"],
        "available_slots": ["11:00", "15:00", "16:00", "18:00"],
    },
    {
        "mentor_id": "mnt_neil", "name": "Neil Verma",
        "avatar": "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "Wildlife Photographer • Ranthambore Fellow",
        "verified": True,
        "achievements": ["Sanctuary Asia Featured", "Wildlife Youth 2024"],
        "subjects": ["Wildlife Photography", "Lightroom", "Composition"],
        "categories": ["photography"],
        "bio": "18 months in the jungle, 12,000 frames. I'll teach you patience, gear, and post-processing.",
        "rating": 4.8, "reviews_count": 39, "sessions": 44, "price": 379,
        "grade_taught": "Grade 8-12", "years": 2, "languages": ["English"],
        "available_slots": ["10:00", "11:00", "17:00", "18:00"],
    },
    # ---- Music ----
    {
        "mentor_id": "mnt_isha", "name": "Isha Bhatt",
        "avatar": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "Trinity Grade 8 • Classical Vocals + Piano",
        "verified": True,
        "achievements": ["Trinity Distinction", "State Music Fest Winner"],
        "subjects": ["Piano", "Music Theory", "Classical Vocals"],
        "categories": ["music"],
        "bio": "Music is my language. From Beethoven to Bollywood, I'll teach you the joy of making music.",
        "rating": 4.9, "reviews_count": 62, "sessions": 71, "price": 299,
        "grade_taught": "Grade 3-12", "years": 4, "languages": ["English", "Hindi", "Marathi"],
        "available_slots": ["16:00", "17:00", "18:00", "19:00"],
    },
    {
        "mentor_id": "mnt_dev", "name": "Dev Malhotra",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "Guitarist • Berklee Summer Scholarship",
        "verified": True,
        "achievements": ["Berklee Summer", "Battle of Bands Winner"],
        "subjects": ["Guitar", "Songwriting", "Music Production"],
        "categories": ["music", "content"],
        "bio": "From playing at school assemblies to Berklee Boston. Let me teach you chords, songs, and stage confidence.",
        "rating": 4.9, "reviews_count": 88, "sessions": 96, "price": 349,
        "grade_taught": "Grade 6-12", "years": 3, "languages": ["English", "Hindi"],
        "available_slots": ["17:00", "18:00", "19:00", "20:00"],
    },
    # ---- Sports ----
    {
        "mentor_id": "mnt_veer", "name": "Veer Singh",
        "avatar": "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1546519638-68e109498ffc?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "State Basketball Captain • Khelo India",
        "verified": True,
        "achievements": ["Khelo India Silver", "State Captain", "SGFI Medalist"],
        "subjects": ["Basketball", "Fitness", "Sports Nutrition"],
        "categories": ["sports"],
        "bio": "Sports is 20% talent 80% grit. I'll help you build both. On-court, off-court, mental game.",
        "rating": 4.8, "reviews_count": 47, "sessions": 51, "price": 299,
        "grade_taught": "Grade 6-12", "years": 2, "languages": ["English", "Hindi", "Punjabi"],
        "available_slots": ["06:00", "07:00", "17:00", "18:00"],
    },
    {
        "mentor_id": "mnt_priya", "name": "Priya Nair",
        "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1526401485004-2fda9f4f7ccc?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "National Chess Master • FIDE Rated",
        "verified": True,
        "achievements": ["FIDE Master", "Under-16 National", "Asian Youth"],
        "subjects": ["Chess Openings", "Endgame", "Tournament Prep"],
        "categories": ["sports", "academics"],
        "bio": "Chess taught me patience, planning, and pattern recognition — the same skills that make you win in life.",
        "rating": 5.0, "reviews_count": 92, "sessions": 108, "price": 379,
        "grade_taught": "Grade 3-12", "years": 4, "languages": ["English", "Malayalam"],
        "available_slots": ["16:00", "17:00", "18:00", "19:00"],
    },
    # ---- Languages ----
    {
        "mentor_id": "mnt_maria", "name": "Maria Fernandes",
        "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "Alliance Francaise B2 • Multilingual Coach",
        "verified": True,
        "achievements": ["DELF B2", "Goethe A2", "TOEFL 118"],
        "subjects": ["French", "German", "IELTS/TOEFL"],
        "categories": ["languages"],
        "bio": "I speak 4 languages fluently. Let me show you my tricks — accent, grammar, conversation confidence.",
        "rating": 4.9, "reviews_count": 68, "sessions": 76, "price": 329,
        "grade_taught": "Grade 6-12", "years": 3, "languages": ["English", "French", "German", "Hindi"],
        "available_slots": ["15:00", "16:00", "17:00", "19:00"],
    },
    # ---- Content Creation ----
    {
        "mentor_id": "mnt_aryan", "name": "Aryan Bhalla",
        "avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "180K YouTuber • Content Strategist",
        "verified": True,
        "achievements": ["Silver Play Button", "Creator Fellowship"],
        "subjects": ["YouTube", "Reels", "Editing", "Personal Branding"],
        "categories": ["content", "entrepreneurship"],
        "bio": "Grew my channel to 180K subs in Class 11. Let me teach you how to create content that ships.",
        "rating": 4.9, "reviews_count": 152, "sessions": 168, "price": 399,
        "grade_taught": "Grade 8-12", "years": 2, "languages": ["English", "Hindi"],
        "available_slots": ["17:00", "18:00", "19:00", "20:00"],
    },
    # ---- AI ----
    {
        "mentor_id": "mnt_saanvi", "name": "Saanvi Rao",
        "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1677442136019-21780ecad995?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "AI Researcher @ IIT-M • Kaggle Competitions Master",
        "verified": True,
        "achievements": ["Kaggle Master", "IIT-M Intern", "Google AI Camp"],
        "subjects": ["Machine Learning", "Python", "Deep Learning"],
        "categories": ["ai", "coding"],
        "bio": "Built my first neural net in Class 10. I'll teach you AI from foundations — no PhD needed.",
        "rating": 5.0, "reviews_count": 96, "sessions": 104, "price": 499,
        "grade_taught": "Grade 9-12", "years": 2, "languages": ["English", "Kannada"],
        "available_slots": ["18:00", "19:00", "20:00", "21:00"],
    },
    # ---- Olympiads ----
    {
        "mentor_id": "mnt_ayaan", "name": "Ayaan Khan",
        "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1509228468518-180dd4864904?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "Chemistry Olympiad Gold • IChO India Rep",
        "verified": True,
        "achievements": ["IChO Silver", "InChO Gold", "NSEC Rank 4"],
        "subjects": ["Chemistry", "Organic Chem", "Physical Chem"],
        "categories": ["olympiads", "academics"],
        "bio": "Chemistry gets easier once you love it. Let me help you build intuition, not just formulas.",
        "rating": 4.9, "reviews_count": 71, "sessions": 79, "price": 429,
        "grade_taught": "Grade 9-12", "years": 2, "languages": ["English", "Hindi", "Urdu"],
        "available_slots": ["17:00", "18:00", "19:00", "20:00"],
    },
    # ---- Public speaking ----
    {
        "mentor_id": "mnt_naina", "name": "Naina Reddy",
        "avatar": "https://images.unsplash.com/photo-1499996860823-5214fcc65f8f?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "TEDx Youth Speaker • JAM Champion",
        "verified": True,
        "achievements": ["TEDx Youth", "Regional JAM Winner", "TOI Debate"],
        "subjects": ["Public Speaking", "Storytelling", "Anchoring"],
        "categories": ["public_speaking", "debate"],
        "bio": "Once too shy to raise my hand. Now I speak on TEDx. I'll show you the exact system I used.",
        "rating": 4.9, "reviews_count": 84, "sessions": 91, "price": 329,
        "grade_taught": "Grade 6-12", "years": 3, "languages": ["English", "Telugu", "Hindi"],
        "available_slots": ["16:00", "17:00", "18:00", "19:00"],
    },
]


SEED_VAULT = [
    {
        "vault_id": "v_business_conclave", "title": "Winning Business Conclave Presentation",
        "collection": "Winning Presentations", "category": "business",
        "author": "Ananya Jain",
        "author_avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 1240, "rating": 4.9, "year": "Class of 2024", "pages": 24, "duration_read": "18 min",
        "description": "The exact deck that won National Business Conclave 2024.",
        "content": "# Winning Business Conclave — HDFC Youth Enterprise 2024\n\n## Slide 1 — The Problem\n78% of Indian teens want to launch a business but only 3% know where to start. The gap: real, hands-on entrepreneurship education inside schools.\n\n## Slide 2 — Our Solution\n**LeadSchool Ventures** — a 12-week micro-venture program for Grades 9-12, embedded inside school timetables. Students form teams, receive ₹5,000 seed capital, and ship a real product to real customers.\n\n## Slide 3 — Market\nTAM: 4.2M students across 12,000 CBSE/ICSE schools. Only 300 currently run any entrepreneurship program.\n\n## Slide 4 — Traction (Pilot Data)\n- 6 schools ran the pilot in 2024\n- 42 student teams launched a business\n- 61% teams broke even in Week 8\n- Average revenue per team: ₹4,800\n\n## Slide 5 — Business Model\nSchools pay ₹499/student per semester. Alumni network + corporate mentors sponsor prize pools. Take rate: 62%.\n\n## Slide 6 — Ask & Roadmap\nSeeking ₹20L seed to scale to 40 schools by 2026. Roadmap: build LMS → recruit 200 alumni mentors → launch inter-school championship.\n\n## Key Learnings (personal notes)\n1. Judges care about traction more than the deck. Have real numbers.\n2. Speak to the problem for 60% of the time.\n3. Practice the demo — a smooth 30s live demo won us the finals.",
    },
    {
        "vault_id": "v_debate_speech", "title": "National Debate Championship Speech",
        "collection": "Debate Speeches", "category": "debate",
        "author": "Arjun Mehta",
        "author_avatar": "https://images.unsplash.com/photo-1544168190-79c17527004f?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 890, "rating": 4.8, "year": "Class of 2023", "pages": 6, "duration_read": "8 min",
        "description": "8-minute finals speech — climate justice motion.",
        "content": "# Speech — 'THBT the Global South should refuse to pay climate reparations without complete debt cancellation'\n\n**Position:** Proposition | **Duration:** 8 min\n\n---\n\nHonorable Chair, worthy opponents, this is not a debate about accounting. This is a debate about **memory** — and about who is finally allowed to remember first.\n\nWe stand today at COP-31 with a bitter irony. The countries that burned the coal, forged the steel, and industrialized on the back of the atmosphere are now asking the countries they colonized to *co-finance* the cleanup.\n\n### Argument 1 — The Ledger Is Older Than the Crisis\n1.2 trillion dollars is the number the IMF wants the Global South to pay by 2030. Do you know what the Global North extracted from just India between 1765 and 1938? **45 trillion dollars.** That's Utsa Patnaik's number, and it's peer reviewed.\n\nWe are being asked to write another cheque on top of the one that was never returned.\n\n### Argument 2 — Debt Is a Weapon\nWhen Pakistan flooded in 2022, 33 million displaced. The IMF's response? A structural adjustment programme. Cut fuel subsidies, cut wheat subsidies. Adapt. Meanwhile Germany reopened coal plants. The atmosphere is a commons; the debt is not.\n\n### Argument 3 — Refusal Is Leverage\nHistory rewards refusal. The Latin American debt crisis of 1982 was broken not by payment, but by collective threats to default. The Jubilee 2000 movement cancelled 100 billion. Refusal creates space. Payment creates precedent.\n\n### Response to Opposition\nMy opponents will argue that refusal risks isolation. I ask them: isolation from whom? From the very institutions that built the crisis? Isolation *is* the moral position when the alternative is complicity.\n\n### Peroration\nColleagues, when history writes about our generation, let it not say we sent a bill to the victim. Let it say we finally, finally, remembered.\n\nI beg to propose.\n\n---\n\n**Coach notes (post-round):**\n- The '45 trillion' stat is your best weapon. Repeat it at least twice.\n- On rebuttals about pragmatism, use the Jubilee 2000 precedent.\n- Slow down at 'This is a debate about memory'. Pause for 2 beats.",
    },
    {
        "vault_id": "v_mun_position", "title": "Harvard MUN Position Paper",
        "collection": "MUN Position Papers", "category": "mun",
        "author": "Advait Sharma",
        "author_avatar": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 1560, "rating": 5.0, "year": "Class of 2024", "pages": 4, "duration_read": "12 min",
        "description": "UNSC — Russia delegate. Best Position Paper award.",
        "content": "# Position Paper — Russian Federation\n**Committee:** United Nations Security Council\n**Agenda:** The Question of Cybersecurity and Sovereign State Actors\n**Delegate:** Advait Sharma, Delhi Public School RK Puram\n\n## Country's Position\nThe Russian Federation categorically rejects the characterization of state-linked cyber activity as inherently aggressive. We view cyberspace as a **fifth sovereign domain** — like land, sea, air, and space — where states retain the right to defend national interest and infrastructure.\n\n## Historical Context\nRussia has been a signatory to every major UN GGE (Group of Governmental Experts) since 2004. In 2011, Russia and China jointly submitted the *International Code of Conduct for Information Security* — a proposal to prohibit the use of ICTs to disrupt political, economic, and social stability. Western nations rejected it. Our position has been consistent since.\n\n## Past Actions\n- 2015: Voted in favour of UN GA Resolution 70/237\n- 2018: Introduced the OEWG (Open-Ended Working Group) — accessible to ALL member states, not just 25 GGE members\n- 2023: Bilateral cyber-agreements with 14 states\n\n## Proposed Solutions\n1. **Universal binding treaty** to replace the fragmented Budapest Convention which excludes 70% of UN members\n2. **Sovereignty-first architecture:** each state governs data of its citizens\n3. **Rejection of attribution based on Western intelligence** — require multilateral evidence review\n\n## Bloc Alignment\nExpected bloc: China, Iran, Belarus, Cuba, Nicaragua, Venezuela. Bridge with India on the sovereignty framing.\n\n## Delegate's War-Room Notes\n- Do NOT concede the term 'cyberattack' — insist on 'cyber-operation'\n- Play defence on Ukraine questions; pivot to Snowden and NSA leaks\n- Working paper strategy: co-sponsor with China, invite India as amendment partner",
    },
    {
        "vault_id": "v_pitch_deck", "title": "Shark Tank Style Pitch Deck",
        "collection": "Pitch Decks", "category": "entrepreneurship",
        "author": "Kabir Rao",
        "author_avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1553877522-43269d4ea984?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 2100, "rating": 4.9, "year": "Class of 2024", "pages": 12, "duration_read": "10 min",
        "description": "The 12-slide deck that got us to the finals.",
        "content": "# Pitch — 'FeedForward' — School Tiffin Redistribution\n\n## 1. Cover\nFeedForward. India's first hyperlocal tiffin redistribution network for schools.\n\n## 2. Hook\nEvery day in Mumbai, 42,000 school tiffins go home half-eaten. Meanwhile 1.6M kids in the same city eat one meal a day.\n\n## 3. Problem\nSchool tiffins are prepared with love but discarded due to picky eating, poor logistics, or dietary mismatch. There's no bridge from surplus to need.\n\n## 4. Solution\nFeedForward is a WhatsApp-first, teacher-mediated protocol that lets students opt-in to donate uneaten (packaged, unopened) tiffin items. Local NGOs collect at 3pm from the school gate. Zero infrastructure change.\n\n## 5. Product Demo (Live)\n60-second live demo: teacher taps 'Donate' → 3 taps → NGO gets confirmation → volunteer arrives at 3:05pm.\n\n## 6. Traction\n- 3 schools running (DPS-RKP, DPS-VK, MIS-Mumbai)\n- 214 daily donations in Week 6\n- 12,000 meals redistributed in 90 days\n- 2 NGOs onboarded (Robin Hood Army, Feeding India)\n\n## 7. Market\n- 42M CBSE students\n- 12,000 schools\n- Estimated 8M tiffins wasted daily\n\n## 8. Business Model\n**Free for schools & students.** Revenue: (a) NGO SaaS ₹99/mo per NGO for analytics, (b) CSR sponsorship — corporate co-branding on donation cards, ₹5/meal.\n\n## 9. Competition\nNo direct competitor. Closest: Feeding India (adult-focused). Our moat: teacher-network + school gate logistics.\n\n## 10. Team\nFounder: Kabir Rao, Class 12. Advisor: Shefali Rao (ex-Zomato).\n\n## 11. Ask\nSeeking ₹15L for 10% equity. Uses: hire 2 ops staff, build teacher WhatsApp bot, scale to 25 schools in Mumbai.\n\n## 12. Vision\nBy 2028, redistribute 100M meals annually across 5000 Indian schools.",
    },
    {
        "vault_id": "v_scholarship", "title": "Ivy League Scholarship Essay",
        "collection": "Scholarship Essays", "category": "academics",
        "author": "Riya Gupta",
        "author_avatar": "https://images.unsplash.com/photo-1618355776464-8666794d2520?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 3400, "rating": 5.0, "year": "Class of 2023", "pages": 3, "duration_read": "7 min",
        "description": "Full-ride to MIT. Read the essay + annotations.",
        "content": "# Common App Personal Essay — MIT '28 Full-Ride Applicant\n**Prompt:** Describe an environment that shaped who you are.\n\n---\n\nMy grandmother owned three saris and forty-two mangoes. The mangoes lived in a jute sack under her bed — one for every grandchild's birthday, five for weddings, twelve for the priest, and a bittersweet handful reserved for what she called 'sudden joys'.\n\nEconomists would call it a rationing system. My grandmother called it *hisaab* — accounting for love.\n\nI didn't know I was going to be an engineer until I was seven, and my grandmother's mango tree got a fungus. The village elders said to cut it down. Amma cried for a week. So I did what any seven-year-old does when they can't sleep — I stole a torch and went to the library.\n\nI didn't find a solution. But I found *questions*. Why did the fungus grow only on humid leaves? Why did the neighbouring guava tree survive? By page 40 of *National Encyclopaedia of Indian Agriculture*, I had a hypothesis. By page 78, I had a plan. By month three, we had lime powder and copper sulphate, and by summer, we had mangoes.\n\nThat mango tree taught me the shape of engineering — that a problem is just an unsolved question, and that curiosity is currency my grandmother had all along.\n\nWhen I built my first neural net at 14, I was still stealing torches, still turning pages. When I coded my first fire-detection sensor for our school library, I remembered that copper sulphate was just chemistry, and chemistry was just love with a spreadsheet.\n\nMIT doesn't need to hear about my JEE rank. My grandmother would have said: 'Beta, ranks fade, mangoes fade, everything fades except the *hisaab* of what you gave back'. So here is my *hisaab*: I want to build climate-resilient agri-sensors for smallholder farmers in the Deccan.\n\nI want the seven-year-old with a torch to keep her mangoes.\n\n---\n\n**Annotations (my own review):**\n1. Grandmother anchor — every essay needs a specific human. Sensory. Concrete.\n2. Numbers > adjectives. '42 mangoes' > 'many mangoes'.\n3. Don't hide the STEM ambition. Show it emerging from something older than achievement.\n4. Come back to the anchor in the closing sentence.\n5. Cut everything that sounds like the Common App told you to write it.",
    },
    {
        "vault_id": "v_xii_notes", "title": "Class XII Physics Complete Notes",
        "collection": "Notes & Study Guides", "category": "academics",
        "author": "Advait Sharma",
        "author_avatar": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1509228468518-180dd4864904?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 5200, "rating": 4.9, "year": "Class of 2024", "pages": 142, "duration_read": "6 hours",
        "description": "Hand-written, board-topper approved.",
        "content": "# Class XII Physics — Complete Notes\n\n## Unit 1: Electrostatics\n### 1.1 Coulomb's Law\nF = k · q1·q2 / r²   where k = 1/(4πε₀) ≈ 9 × 10⁹ Nm²/C²\n\n**Board tip:** They love the vector form. Always write F⃗ = k · (q1q2/r²) · r̂\n\n### 1.2 Electric Field due to a Dipole\n- Axial: E = 2kp / r³  (along dipole moment)\n- Equatorial: E = -kp / r³  (opposite to p)\n\n### 1.3 Gauss's Law\n∮ E⃗ · dA⃗ = q_enc / ε₀\n\n**Applications:** Line charge (E = λ/2πε₀r), Sheet (E = σ/2ε₀), Sphere.\n\n## Unit 2: Current Electricity\n### Drift velocity\nv_d = eE·τ/m ; I = neAv_d\n\n### Wheatstone Bridge — balanced condition\nP/Q = R/S\n\n### Meter bridge derivation — 5-mark question favourite. Learn by heart.\n\n## Unit 3: Magnetism\n### Biot-Savart\ndB⃗ = (μ₀/4π) · I dL⃗ × r̂ / r²\n\n### Ampere's Circuital Law: for solenoid → B = μ₀nI\n\n## Unit 4: EMI & AC\n### Motional EMF\nε = BLv\n\n### AC through inductor & capacitor — draw phasor diagrams.\n\n## Unit 5: Optics — most weightage, learn diagrams.\n### Lens Formula\n1/v - 1/u = 1/f\n\n### Refractive index in a prism at min. deviation: n = sin((A+δm)/2) / sin(A/2)\n\n## Unit 6: Modern Physics\n### de Broglie λ = h/p\n### Einstein's photoelectric: KE_max = hν - φ\n\n---\n\n### Board Question Bank (last 5 years' pattern)\n1. Derive E for axial dipole — 3 marks (every year)\n2. Meter bridge — 5 marks (2019, 2021, 2023)\n3. Cyclotron working — 3 marks (2020, 2022)\n\n**Advait's exam-hall protocol:**\n- 5 min pure reading — mark 5-mark questions\n- Answer diagram Qs first (faster marks)\n- 2 min buffer at the end for units/directions\n- If stuck, write the formula. It earns 1 mark almost always.",
    },
    {
        "vault_id": "v_case_study", "title": "Startup Case Study: 0 to 10Cr",
        "collection": "Pitch Decks", "category": "entrepreneurship",
        "author": "Kabir Rao",
        "author_avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 780, "rating": 4.7, "year": "Class of 2024", "pages": 18, "duration_read": "22 min",
        "description": "Full playbook — validation, MVP, GTM, first 100 users.",
        "content": "# Case Study — How I got FeedForward from 0 to ₹10 lakh MRR in 11 months\n\n## Month 1-2: Validation (No Product)\n- Interviewed 47 teachers across 6 schools. Not a single one had heard of tiffin donation.\n- Ran a 'fake door' test: WhatsApp form asking 'would you donate?'. 62% said yes.\n- Insight: The bottleneck was NOT willingness. It was logistics.\n\n## Month 3-4: The MVP\n- Bought a burner Android for ₹3,500 and hosted a WhatsApp business account\n- Used Google Sheets as a backend. No app.\n- Manually coordinated donations at DPS-RKP for 6 weeks. Broke even at Week 3.\n\n## Month 5-6: The First Real Product\n- Hired 1 engineer part-time from IIIT-D\n- Shipped v1 in 21 days: teacher app + NGO dashboard\n- First school-wide rollout: 800 students, 214 daily donations in Week 2\n\n## Month 7: The Anti-Playbook Moment\n- I tried to raise pre-seed. Every VC said 'not scalable'.\n- Pivoted to selling to schools directly as CSR upgrade — ₹499/student/semester\n- First 3 schools signed. LTV/CAC ratio: 8.2×\n\n## Month 8-11: Compound\n- Cold-emailed 200 school principals. 12 replied. 5 signed. Repeat-referral kicked in.\n- Hit ₹10L MRR in Month 11 across 22 schools\n\n## Lessons (learned the hard way)\n1. Talk to 40+ users before writing a line of code.\n2. Manual is beautiful. Ship the ugliest thing that solves the pain.\n3. VCs are not oracles. Sometimes 'not scalable' just means 'not obvious to me'.\n4. First 100 customers are always sold by the founder. There are no shortcuts.\n5. The best growth channel is the one your competitors are too cool to use. Ours: WhatsApp.",
    },
    {
        "vault_id": "v_design_portfolio", "title": "NID Design Portfolio 2024",
        "collection": "Winning Presentations", "category": "design",
        "author": "Meera Iyer",
        "author_avatar": "https://images.unsplash.com/photo-1580489944761-15a19d654956?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1558655146-9f40138edfeb?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 640, "rating": 4.9, "year": "Class of 2024", "pages": 32, "duration_read": "20 min",
        "description": "The portfolio that cracked NID Ahmedabad.",
        "content": "# NID Design Portfolio — Meera Iyer\n\n## Portfolio Philosophy\nNID doesn't want polished agency work. They want to see how you *think*.\n\n## Piece 1 — Observational sketching (Chennai fish market, 6am)\n40 sketches in a spiral pad. Charcoal, no eraser. Selected 6 for the folio. Note: they marked 'grip' on the fish vendor's hand — that specificity is the point.\n\n## Piece 2 — Redesign a chai kettle for a paraplegic vendor\nProblem: existing kettles require two hands to pour. My redesign: single-hand lever mechanism. Sold two units to real vendors in Adyar. NID loved the field-testing.\n\n## Piece 3 — Type in the wild\n52 photographs of Tamil signage across Chennai, categorized by street function (kirana, hardware, temple). NID adores India-first typography exploration.\n\n## Piece 4 — Personal object narrative\n7-page zine about my grandmother's tiffin box. Object → memory → design principle → application.\n\n## Piece 5 — Interactive prototype\nA cardboard Braille cookbook. 3 recipes. Users can 'taste-test' navigate with fingertips.\n\n---\n\n### DAT (Studio Test) Debrief\n- Question was: design a public bench for a hilly city with a monsoon problem\n- I drew 12 concepts, picked 3, prototyped in cardboard, presented in 40 min\n- Judges probed: 'What if pigeon droppings?' — I had thought of it and had a sacrificial top layer. Won the interview here.\n\n### Interview\nThey ask about your influences. Have 3 non-obvious ones. Mine were: Sonia Delaunay, Chennai auto-rickshaw art, and Charles Correa.\n\n### Do NOT do\n- Photoshop mockups without process\n- 'Client work' that looks like a marketing agency\n- Too much digital. Bring pencils.",
    },
    {
        "vault_id": "v_debate_prep", "title": "Cambridge-Style Debate Prep Kit",
        "collection": "Debate Speeches", "category": "debate",
        "author": "Ananya Jain",
        "author_avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1544531586-fde5298cdd40?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 420, "rating": 4.8, "year": "Class of 2024", "pages": 22, "duration_read": "35 min",
        "description": "Templates, rebuttal frameworks, timing drills.",
        "content": "# Cambridge / BP Debate Prep — Complete Kit\n\n## The 4-Corner Framework\nEvery motion has 4 stakeholders. Map them before writing:\n1. The moved-against (who loses)\n2. The moved-for (who wins)\n3. The state (enforcer)\n4. Third-parties (unintended consequences)\n\n## The AREA Template for a Constructive\n- **A**ssertion (10s)\n- **R**easoning (30s)\n- **E**vidence (30s)\n- **A**nalysis (60s)\n\n## Rebuttal Ladders\n1. **Deny the fact** — 'This premise is empirically false'\n2. **Grant the fact, deny the significance** — 'True, but 3% is not a policy problem'\n3. **Grant significance, deny the causation** — 'Poverty correlates but does not cause'\n4. **Grant the causation, deny the solution** — 'Even if the mechanism holds, this policy fails'\n\n## Speaker Roles (BP)\n- **Prime Minister:** Definition + case + 1st substantive\n- **Leader of Opp:** Rebuttal + 1st Opp substantive\n- **Deputy PM:** Extension of gov case + rebuttal\n- **Deputy LO:** Extension + rebuttal\n- **Members:** New substantive (extension) — the pivot round\n- **Whips:** No new matter, comparative worlds only\n\n## Practice Timing (my exact schedule)\n- 15 min prep\n- Speak 7 min per speech\n- Debrief 10 min after every round\n- Repeat 3× per week\n\n## Ananya's Signature Openers\n1. 'History does not forgive the well-intentioned. It forgives only the effective.'\n2. 'Every progressive policy in this house has one thing in common — it was called radical the day before it became obvious.'\n3. 'Let's begin with a fact my opponents have generously overlooked...'\n\n## Killers (avoid)\n- 'It is my belief that...' — REPLACE with 'The evidence shows...'\n- 'Everyone knows...' — never true, never a warrant\n- Excessive filler ('so, basically, kind of')\n\n## Final round prep\n- Two hours before: no new content. Read old speeches aloud.\n- Warm-up: 1 min JAM on any random topic\n- Water > coffee",
    },
    # Extra vault items
    {
        "vault_id": "v_photo_portfolio", "title": "NatGeo Young Photographer Portfolio",
        "collection": "Winning Presentations", "category": "photography",
        "author": "Zara Kapoor",
        "author_avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 510, "rating": 4.9, "year": "Class of 2024", "pages": 20, "duration_read": "12 min",
        "description": "10-image folio + captions + technical notes.",
        "content": "# NatGeo Young Photographer — Selected Portfolio\n\n## Frame 1 — Kolkata potter, 4:47am\nFujifilm X100V | ISO 800 | f/2 | 1/60s\nHand-held, no flash. Rembrandt lighting from the kiln fire.\n\n## Frame 2 — Ganga aarti reflection\nShot from a boat, waited 40 minutes for the reflection to steady. Used a 3-stop ND to slow down the fire trails.\n\n## Frame 3 — Nizamuddin qawwali night\nISO 3200 pushed +1. Grain is the point.\n\n## Frame 4 — The tea seller who wouldn't smile\nStreet portrait ethics: I bought 3 chais, sat for an hour, asked before I clicked. He never smiled. That's the image.\n\n## Frame 5 — Empty Kashmir bus stop, curfew\n21mm wide. The frame is 80% negative space. That is the essay.\n\n## Judge's notes (recovered from feedback letter)\n'The strongest folios avoid the picturesque. Zara's does. She waits for people to become themselves.'\n\n## Post-production philosophy\n- Never touch highlights past +5\n- Zero saturation boosts. Colour is either there in the light or not.\n- Print at 8×12. Digital ruins detail.",
    },
    {
        "vault_id": "v_ai_project", "title": "Kaggle-Winning ML Project Writeup",
        "collection": "Notes & Study Guides", "category": "ai",
        "author": "Saanvi Rao",
        "author_avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1677442136019-21780ecad995?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 940, "rating": 5.0, "year": "Class of 2024", "pages": 14, "duration_read": "18 min",
        "description": "End-to-end ML pipeline for skin lesion classification.",
        "content": "# Kaggle Bronze — Skin Lesion Detection\n\n## Dataset\nHAM10000 — 10,015 dermatoscopic images, 7 classes.\n\n## Pipeline\n1. Stratified 80/10/10 split\n2. Aggressive augmentation: RandAugment(N=2, M=9)\n3. Backbone: EfficientNet-V2-S, ImageNet pretrained\n4. Head: Global-pool → Dropout(0.3) → Linear\n5. Loss: Focal Loss (γ=2) due to class imbalance\n6. Optimizer: AdamW, lr=3e-4, cosine schedule\n\n## What Worked\n- **Test-time augmentation (TTA×8)**: +2.3 F1\n- **Pseudo-labelling** on unlabelled ISIC-2020: +1.1 F1\n- Two-stage training: freeze → unfreeze\n\n## What Didn't\n- Vision transformers (too data-hungry for 10k)\n- MixUp (hurt melanoma recall)\n- Ensembles beyond 3 models — plateaued\n\n## Final Score\nPublic LB: 0.8721 | Private LB: 0.8694 → **Bronze**\n\n## Code snippet — the winning trick\n```python\n# Class-balanced focal loss\ndef focal_loss(logits, target, alpha, gamma=2.0):\n    ce = F.cross_entropy(logits, target, reduction='none', weight=alpha)\n    pt = torch.exp(-ce)\n    return ((1-pt)**gamma * ce).mean()\n```\n\n## Reflection\nI spent 60% of time on data cleaning, 20% on augmentation, 15% on baseline, 5% on the winning idea. That ratio is the real learning.",
    },
    {
        "vault_id": "v_music_theory", "title": "Trinity Grade 8 Piano — Prep Notes",
        "collection": "Notes & Study Guides", "category": "music",
        "author": "Isha Bhatt",
        "author_avatar": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 320, "rating": 4.8, "year": "Class of 2024", "pages": 18, "duration_read": "25 min",
        "description": "Complete practice log + scale patterns + exam pieces.",
        "content": "# Trinity Grade 8 Piano — Preparation Playbook\n\n## Repertoire I chose\n- Group A: Bach — Prelude in E Minor BWV 855a (technical exposure)\n- Group B: Beethoven — Sonatina in G, mvt 1 (drama & phrasing)\n- Group C: Ludovico Einaudi — Nuvole Bianche (emotional expression)\n\n## Daily Practice Structure (90 min)\n- Warm-up (15): Hanon 1-6, chromatic scale, arpeggios in all 24 keys\n- Slow section work (30): sections at 60% tempo\n- Full run-throughs (30)\n- Sight-reading (10) — Grade 6 pieces\n- Aural (5)\n\n## Common Trinity trip-ups\n1. **Aural rhythm-echo** — practice with a metronome ticking upbeats, not downbeats\n2. **Sight-reading** — read *ahead* by 2 beats always\n3. **Improvisation** — plan a chord progression (I-vi-IV-V) as your safety net\n\n## The examiner's psychology\nThey want you to LOVE what you're playing. Sit at the piano for 3 seconds before starting. Close your eyes for one breath. Then begin.\n\n## Mental prep\n- Night before: no new material. Play the pieces in your head, hands off.\n- Morning of: eat protein, no caffeine, one 20-min run of full pieces.\n- Warm up on the exam-hall piano for exactly the time they give you. No more.",
    },
    {
        "vault_id": "v_sop_college", "title": "MIT Application SOP",
        "collection": "Scholarship Essays", "category": "academics",
        "author": "Riya Gupta",
        "author_avatar": "https://images.unsplash.com/photo-1618355776464-8666794d2520?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 1120, "rating": 4.9, "year": "Class of 2023", "pages": 2, "duration_read": "5 min",
        "description": "Why-MIT + Why-CS in 650 words.",
        "content": "# MIT Application — Why MIT / Why CSE\n\nWhen I discovered that MIT's building 32 has a rain gutter installed by students in the 1960s that still directs water into a specific coffee mug on the loading dock, I understood the culture I wanted to live inside.\n\nMIT does not confuse cleverness with importance. It does not ask its students to be impressive. It asks them to *notice*.\n\nI have spent three years building small, useless, and beloved things. A Python bot that reminds our house-help to take her medicine in Bengali. A humidity sensor that saved my grandmother's mango tree. A CNN that told me — 62% confidence — that our neighbour's cat had thyroid issues (it did).\n\nMIT's undergraduate CS program is not about the ranking. It is about the professors who still return emails from unknown 17-year-olds at midnight. It is about UROP — a structure that treats an undergraduate as intellectually deserving of a lab. It is about 6.006 taught by someone who wrote the book. It is about pset partners who become co-founders.\n\nI want to work in the Sertac Karaman lab on climate-resilient robotic agriculture. I want to take 6.036 with Bhattacharya. I want to fail an olympiad-level pset for the first time in my life.\n\nThe kids I want to spend four years with are the kids who set that rain gutter to hit that mug. Not because they were told to. Because they saw the geometry and could not un-see it.\n\nI want to add one small useless beloved thing to that campus. I hope MIT lets me.",
    },
    {
        "vault_id": "v_speech_tedx", "title": "TEDx Youth Speech Transcript",
        "collection": "Debate Speeches", "category": "public_speaking",
        "author": "Naina Reddy",
        "author_avatar": "https://images.unsplash.com/photo-1499996860823-5214fcc65f8f?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 890, "rating": 4.9, "year": "Class of 2024", "pages": 4, "duration_read": "11 min",
        "description": "'The invisible curriculum' — my TEDx talk transcript.",
        "content": "# TEDxYouth Speech — 'The Invisible Curriculum'\n\nMy school teaches me Physics.\n\nBut my school does not teach me how to sit in a room with someone I disagree with, and stay curious. This is the invisible curriculum, and every student is failing it — because we never take the test.\n\nWhen I was 14 I was the second-worst public speaker in my class. Not because I was quiet. But because my throat closed every time I looked at 40 faces. So I did what any 14-year-old does — I lied. I said I was 'saving my voice'. For eight months, I did not raise my hand once.\n\nThen one Thursday my history teacher, Ms. Menon, asked me to stay back. She did not give me a pep talk. She gave me a rulebook. 'Naina', she said, 'every time you don't speak, someone else has to speak for you. Someone with less to say. Do you agree with that arrangement?'\n\nThat sentence unlocked something. Silence, I realized, is not neutral. Silence is a vote. And it is almost never a vote for what you actually believe.\n\nI joined MUN two months later. I lost every round for a year. But I also started to notice — the people who won weren't the loudest. They were the ones who were not afraid to be wrong out loud.\n\nHere is the invisible curriculum. It is the courage to be publicly imperfect. It is the muscle to say 'I don't know yet' without shame. It is the willingness to change your mind mid-sentence.\n\nWe train for the IIT-JEE. We train for the boards. We train for the SAT. We do not train for the moment when someone asks us, in a job interview or a first date or a wedding speech or a parliament, 'What do you think?'\n\nSo here is my proposal. Every school in India should have a 'Silence Tax'. One hour a week, where students are graded not on what they know, but on what they are willing to say in front of others who might disagree.\n\nWe should build the muscle in Class 6. Not in the boardroom at 26.\n\nThank you.\n\n---\n\n**Delivery notes (my own):**\n- Pauses at 'Silence is a vote.' — 2 full seconds\n- Look at 3 different sections of the audience\n- Slow down at the closing 'Class 6, not 26'\n- Never rehearse the last line — let it come alive on stage",
    },
    {
        "vault_id": "v_hackathon_repo", "title": "48-hr Hackathon — Winning Submission",
        "collection": "Pitch Decks", "category": "coding",
        "author": "Saanvi Rao",
        "author_avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1531545514256-b1400bc00f31?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 620, "rating": 4.8, "year": "Class of 2024", "pages": 8, "duration_read": "12 min",
        "description": "How we shipped a full-stack app in 48 hours.",
        "content": "# HackJIIT '24 — Winner (Best Solo Track)\n\n## Idea (Hour 0-2)\nA voice-first study companion for visually impaired students. Reads NCERT chapters, quizzes, and voice-based revision.\n\n## Stack Choice (Hour 2-3)\n- React Native (voice input via expo-speech + expo-audio)\n- FastAPI backend\n- Claude Sonnet for summarization\n- Whisper for STT\n\n## Timeline\n- **Hour 3-16:** Ship a walking skeleton — one chapter of NCERT Class 10 Science, voice questions, voice replies\n- **Hour 16-24:** Sleep 4 hours\n- **Hour 24-30:** Add quiz mode + accessibility polish\n- **Hour 30-40:** Demo scripting, edge case testing\n- **Hour 40-44:** Sleep 2 hours\n- **Hour 44-48:** Pitch prep, live demo dry runs\n\n## What won it\n- A live demo with a real visually impaired student from our school\n- Judges saw the empathy, not the code\n\n## Post-mortem\n- Do NOT over-scope. We cut 3 features by Hour 12 and never regretted it.\n- Have ONE person who owns the demo script. That person doesn't code in the last 4 hours.\n- Bring headphones. Voice apps + hackathons + 200 people = disaster.",
    },
    {
        "vault_id": "v_language_ielts", "title": "IELTS 8.5 Prep Strategy",
        "collection": "Notes & Study Guides", "category": "languages",
        "author": "Maria Fernandes",
        "author_avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 440, "rating": 4.9, "year": "Class of 2024", "pages": 10, "duration_read": "16 min",
        "description": "Section-wise breakdown of how I hit 8.5 overall.",
        "content": "# IELTS 8.5 — My Exact Prep\n\n## Timeline: 6 weeks, 90 min/day\n\n### Listening (9.0)\n- Watched BBC World News daily. Wrote 100-word summaries.\n- Did all 4 Cambridge test books, timed.\n- Fatal mistake: not double-checking spelling in Section 1. Cost 1 mark in mocks. Never in real exam.\n\n### Reading (8.5)\n- Read The Economist twice a week. Underlined signposts.\n- Skimming: 90s per passage. Question-first strategy.\n- True/False/Not Given is the killer. If you can't find explicit contradiction, it's Not Given.\n\n### Writing (7.5)\n- Task 1: Learn 5 templates for the 5 chart types.\n- Task 2: 4-paragraph structure. Body 1 = agree case; Body 2 = disagree case; conclusion = your reasoned position.\n- Practice 8 essays, get 2 professionally reviewed.\n\n### Speaking (8.5)\n- Record every practice. Delete all 'um', 'like', 'basically' from your voice.\n- Part 2: 2-min monologue. Prepare 15 topic templates that you can twist to fit any prompt.\n- Never speak in memorized paragraphs. Examiners smell them.\n\n## Exam day\n- Eat carbs 90 min before\n- Reach 30 min early\n- Speak to the taxi driver in English on the way — warm up your voice\n\n## The one hack no one shares\nIn Speaking Part 3, disagreeing with the examiner's premise politely earns you band 8+. Do it once, once only.",
    },
]


SEED_CAREERS = [
    {"career_id": "car_marketing", "name": "Marketing", "icon": "trending-up", "color": "#F97316",
     "tagline": "Build brands. Shape culture.",
     "description": "Marketers understand people, craft campaigns, and drive growth.",
     "top_colleges": ["IIM Ahmedabad", "SP Jain", "NMIMS", "Wharton", "Kellogg"],
     "skills": ["Communication", "Creativity", "Analytics", "Storytelling"],
     "salary_range": "₹6-40 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Read Seth Godin, run a school Instagram."},
                 {"stage": "Grade 11-12", "action": "Ace English & Business Studies."},
                 {"stage": "College", "action": "BBA / BMS, then MBA in Marketing."},
                 {"stage": "Career", "action": "Brand manager → CMO → Founder."}],
     "day_in_life": "Standups, brand reviews, creative reviews, data dashboards."},
    {"career_id": "car_finance", "name": "Finance", "icon": "trending-up", "color": "#10B981",
     "tagline": "Master money. Move markets.",
     "description": "Finance runs the world. Learn how capital flows.",
     "top_colleges": ["SRCC", "St. Xavier's", "IIM", "LSE", "Wharton"],
     "skills": ["Excel", "Accounting", "Valuation", "Statistics"],
     "salary_range": "₹8-50 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Learn basic accounting."},
                 {"stage": "Grade 11-12", "action": "Commerce + Maths. CA Foundation."},
                 {"stage": "College", "action": "B.Com, CFA Level 1."},
                 {"stage": "Career", "action": "Analyst → VP → MD."}],
     "day_in_life": "Financial models, market news, client calls."},
    {"career_id": "car_law", "name": "Law", "icon": "hammer", "color": "#2563EB",
     "tagline": "Argue with logic. Change society.",
     "description": "Law shapes democracy, business, and human rights.",
     "top_colleges": ["NLSIU Bangalore", "NALSAR", "NLU Delhi", "Harvard Law"],
     "skills": ["Reading", "Writing", "Debating", "Logical Reasoning"],
     "salary_range": "₹8-80 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Debate, MUN, newspapers."},
                 {"stage": "Grade 11-12", "action": "CLAT prep."},
                 {"stage": "College", "action": "5-year BA LLB from NLU."},
                 {"stage": "Career", "action": "Associate → Partner → Judge."}],
     "day_in_life": "Case research, drafting, courtroom."},
    {"career_id": "car_medicine", "name": "Medicine", "icon": "medkit", "color": "#EF4444",
     "tagline": "Heal. Discover. Serve.",
     "description": "Doctors save lives and push human health forward.",
     "top_colleges": ["AIIMS", "CMC Vellore", "JIPMER", "Harvard Med"],
     "skills": ["Biology", "Empathy", "Precision", "Endurance"],
     "salary_range": "₹8-60 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Biology + Chemistry."},
                 {"stage": "Grade 11-12", "action": "NEET prep. PCB core."},
                 {"stage": "College", "action": "MBBS → MD/MS."},
                 {"stage": "Career", "action": "Resident → Consultant → Head."}],
     "day_in_life": "OPD, rounds, surgeries, research."},
    {"career_id": "car_engineering", "name": "Engineering", "icon": "construct", "color": "#8B5CF6",
     "tagline": "Build the future.",
     "description": "Engineers solve real-world problems with math, code, and grit.",
     "top_colleges": ["IIT Bombay/Delhi", "BITS Pilani", "IIIT-H", "MIT", "Stanford"],
     "skills": ["Math", "Physics", "Coding", "Problem Solving"],
     "salary_range": "₹10-80 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "NTSE prep. Python."},
                 {"stage": "Grade 11-12", "action": "JEE / SAT. Side projects."},
                 {"stage": "College", "action": "B.Tech CS/EE/ME."},
                 {"stage": "Career", "action": "SDE → Sr → Founder/CTO."}],
     "day_in_life": "Standups, code reviews, design docs."},
    {"career_id": "car_design", "name": "Design", "icon": "color-palette", "color": "#EC4899",
     "tagline": "Where art meets impact.",
     "description": "Designers craft experiences that millions use.",
     "top_colleges": ["NID Ahmedabad", "IIT Bombay IDC", "RISD", "Parsons"],
     "skills": ["Sketching", "Empathy", "Figma", "Systems Thinking"],
     "salary_range": "₹6-60 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Sketch daily. Figma."},
                 {"stage": "Grade 11-12", "action": "Portfolio. NID/UCEED prep."},
                 {"stage": "College", "action": "B.Des."},
                 {"stage": "Career", "action": "Designer → Lead → Head of Design."}],
     "day_in_life": "Sketching, prototyping, critiques."},
    {"career_id": "car_pilot", "name": "Pilot", "icon": "airplane", "color": "#0EA5E9",
     "tagline": "Own the skies.",
     "description": "Pilots operate one of the most complex machines built.",
     "top_colleges": ["IGRUA", "Bombay Flying Club", "CAE Oxford"],
     "skills": ["Physics", "Focus", "Decision Making", "Health"],
     "salary_range": "₹15-100 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "PCM strong. Class 1 Medical."},
                 {"stage": "Grade 11-12", "action": "12th PCM + DGCA prep."},
                 {"stage": "College", "action": "CPL — 200 flying hours."},
                 {"stage": "Career", "action": "First Officer → Captain."}],
     "day_in_life": "Pre-flight checks, flying, layovers."},
    {"career_id": "car_entrepreneur", "name": "Entrepreneurship", "icon": "rocket", "color": "#F59E0B",
     "tagline": "Build something that matters.",
     "description": "Entrepreneurs turn ideas into companies that shape the world.",
     "top_colleges": ["Stanford", "IIM", "Wharton (optional)"],
     "skills": ["Grit", "Sales", "Product Sense", "Fundraising"],
     "salary_range": "₹0 to ∞",
     "roadmap": [{"stage": "Grade 9-10", "action": "Sell something. Learn to code."},
                 {"stage": "Grade 11-12", "action": "Ship a small product."},
                 {"stage": "College", "action": "Apply to YC / Antler."},
                 {"stage": "Career", "action": "Founder → Scale → Next venture."}],
     "day_in_life": "Selling, hiring, fundraising, firefighting."},
    # NEW careers
    {"career_id": "car_ai_research", "name": "AI / ML Research", "icon": "sparkles", "color": "#7C3AED",
     "tagline": "Teach machines to think.",
     "description": "Push the frontier of intelligence — vision, language, robotics, agents.",
     "top_colleges": ["IIT-Madras (AI)", "IIIT-Hyderabad", "CMU", "MIT", "Stanford AI"],
     "skills": ["Linear Algebra", "Python", "PyTorch", "Research Writing"],
     "salary_range": "₹15-150 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Learn Python + basic stats."},
                 {"stage": "Grade 11-12", "action": "Kaggle competitions, read papers."},
                 {"stage": "College", "action": "CS with AI/ML electives, publish."},
                 {"stage": "Career", "action": "Research Eng → MLE → Founder / PhD."}],
     "day_in_life": "Read papers, run experiments, write code, publish."},
    {"career_id": "car_data_science", "name": "Data Science", "icon": "stats-chart", "color": "#0891B2",
     "tagline": "Turn data into decisions.",
     "description": "Extract insight and predictions from data at scale.",
     "top_colleges": ["ISI Kolkata", "IIT Roorkee", "CMU", "Berkeley"],
     "skills": ["Statistics", "Python", "SQL", "Storytelling"],
     "salary_range": "₹10-60 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Excel wizardry, basic Python."},
                 {"stage": "Grade 11-12", "action": "Learn SQL, Kaggle beginner."},
                 {"stage": "College", "action": "Stats/CS major, internships."},
                 {"stage": "Career", "action": "Analyst → DS → Head of Data."}],
     "day_in_life": "SQL queries, dashboards, models, stakeholder meetings."},
    {"career_id": "car_medicine_research", "name": "Biomedical Research", "icon": "flask", "color": "#DC2626",
     "tagline": "Cure the incurable.",
     "description": "From cancer immunotherapy to CRISPR — build the future of health.",
     "top_colleges": ["AIIMS", "IISc Bangalore", "NCBS", "Harvard", "Stanford"],
     "skills": ["Biology", "Chemistry", "Research", "Patience"],
     "salary_range": "₹8-50 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Biology + Chemistry deep dive."},
                 {"stage": "Grade 11-12", "action": "KVPY, INBO."},
                 {"stage": "College", "action": "BS-MS at IISER + research."},
                 {"stage": "Career", "action": "PhD → Postdoc → PI."}],
     "day_in_life": "Wet lab, data analysis, paper writing."},
    {"career_id": "car_ca", "name": "Chartered Accountant", "icon": "calculator", "color": "#059669",
     "tagline": "The language of business.",
     "description": "Audit, tax, advisory — the most trusted profession in business.",
     "top_colleges": ["ICAI (India)", "ACCA (Global)"],
     "skills": ["Numeracy", "Attention to Detail", "Ethics"],
     "salary_range": "₹8-50 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Commerce Foundation."},
                 {"stage": "Grade 11-12", "action": "CA Foundation."},
                 {"stage": "College", "action": "CA Intermediate + Articleship."},
                 {"stage": "Career", "action": "CA → Partner → CFO."}],
     "day_in_life": "Audits, tax planning, client calls, filings."},
    {"career_id": "car_journalism", "name": "Journalism", "icon": "newspaper", "color": "#B91C1C",
     "tagline": "Speak truth to power.",
     "description": "Long-form, investigative, or broadcast — journalism shapes democracies.",
     "top_colleges": ["ACJ Chennai", "IIMC", "Columbia J-School"],
     "skills": ["Writing", "Interviewing", "Skepticism", "Speed"],
     "salary_range": "₹5-40 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Write for school paper."},
                 {"stage": "Grade 11-12", "action": "Intern at a local newsroom."},
                 {"stage": "College", "action": "BA Journalism / English + fellowships."},
                 {"stage": "Career", "action": "Reporter → Editor → Founder."}],
     "day_in_life": "Interviews, field visits, deadline crunches."},
    {"career_id": "car_psychology", "name": "Psychology", "icon": "happy", "color": "#DB2777",
     "tagline": "Understand the human mind.",
     "description": "Clinical, research, or organizational — psychology sits at every crossroads.",
     "top_colleges": ["Lady Shri Ram", "Christ University", "Harvard Psych"],
     "skills": ["Empathy", "Research", "Communication", "Data"],
     "salary_range": "₹5-35 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Read psychology books."},
                 {"stage": "Grade 11-12", "action": "Psychology as elective."},
                 {"stage": "College", "action": "BA Psych, then M.A. or M.Phil clinical."},
                 {"stage": "Career", "action": "Therapist → PhD → Prof / Founder."}],
     "day_in_life": "Client sessions, case notes, research reading."},
    {"career_id": "car_architect", "name": "Architecture", "icon": "business", "color": "#EA580C",
     "tagline": "Shape space. Shape life.",
     "description": "From homes to skylines — architecture is applied art at scale.",
     "top_colleges": ["CEPT", "SPA Delhi", "IIT Kharagpur", "Harvard GSD"],
     "skills": ["Drawing", "3D Visualization", "Physics", "Creativity"],
     "salary_range": "₹6-40 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Sketch daily."},
                 {"stage": "Grade 11-12", "action": "PCM + NATA/JEE Arch prep."},
                 {"stage": "College", "action": "5-year B.Arch."},
                 {"stage": "Career", "action": "Associate → Lead Architect → Firm Partner."}],
     "day_in_life": "Site visits, drafting, client meetings, model-making."},
    {"career_id": "car_content_creator", "name": "Content Creator", "icon": "videocam", "color": "#F43F5E",
     "tagline": "Build an audience. Build a business.",
     "description": "Creators run modern media companies — of one.",
     "top_colleges": ["Not required — internet is the school"],
     "skills": ["Storytelling", "Editing", "Consistency", "Analytics"],
     "salary_range": "₹0 – ₹∞ (creator earnings vary wildly)",
     "roadmap": [{"stage": "Grade 9-10", "action": "Pick a niche. Post weekly."},
                 {"stage": "Grade 11-12", "action": "Ship 100 pieces of content."},
                 {"stage": "College", "action": "Monetize + brand deals."},
                 {"stage": "Career", "action": "Creator → Studio → Media brand."}],
     "day_in_life": "Ideate, film, edit, publish, respond, repeat."},
    {"career_id": "car_civil_services", "name": "Civil Services", "icon": "shield-checkmark", "color": "#1E40AF",
     "tagline": "Serve at scale.",
     "description": "IAS/IPS/IFS — the most impactful careers in Indian governance.",
     "top_colleges": ["Any UG + UPSC prep"],
     "skills": ["General Awareness", "Writing", "Ethics", "Leadership"],
     "salary_range": "₹8-25 LPA (impact >> salary)",
     "roadmap": [{"stage": "Grade 9-10", "action": "Read newspapers deeply."},
                 {"stage": "Grade 11-12", "action": "GK, essay writing."},
                 {"stage": "College", "action": "Any UG, start optional subject."},
                 {"stage": "Career", "action": "UPSC → District → State → Centre."}],
     "day_in_life": "Field visits, policy writing, review meetings, community engagement."},
    {"career_id": "car_scientist", "name": "Research Scientist", "icon": "flask", "color": "#7C3AED",
     "tagline": "Push the frontier of what we know.",
     "description": "Physics, chemistry, biology, astronomy — a life in discovery.",
     "top_colleges": ["IISc", "IISER", "TIFR", "Caltech", "MIT"],
     "skills": ["Deep Focus", "Math", "Curiosity", "Writing"],
     "salary_range": "₹6-40 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Olympiads, science fair."},
                 {"stage": "Grade 11-12", "action": "KVPY, NSEP/NSEC/NSEB."},
                 {"stage": "College", "action": "BS-MS + summer research."},
                 {"stage": "Career", "action": "PhD → Postdoc → Faculty."}],
     "day_in_life": "Experiments, papers, teaching, grants."},
    {"career_id": "car_athlete", "name": "Professional Athlete", "icon": "basketball", "color": "#0891B2",
     "tagline": "Turn passion into performance.",
     "description": "From cricket to chess, esports to Olympics — sport as a career.",
     "top_colleges": ["Khelo India Centres", "SAI", "NIS Patiala"],
     "skills": ["Discipline", "Physical Fitness", "Mental Toughness"],
     "salary_range": "₹5 LPA – ₹100+ Cr",
     "roadmap": [{"stage": "Grade 9-10", "action": "Train 15 hrs/week."},
                 {"stage": "Grade 11-12", "action": "State-level competition."},
                 {"stage": "College", "action": "National-level + college scholarships."},
                 {"stage": "Career", "action": "Pro contract → International → Coaching."}],
     "day_in_life": "Training, matches, physio, mental prep."},
    {"career_id": "car_musician", "name": "Musician", "icon": "musical-notes", "color": "#DB2777",
     "tagline": "Play. Compose. Perform.",
     "description": "Performer, composer, producer — a life in music.",
     "top_colleges": ["KM Music Conservatory", "Trinity", "Berklee"],
     "skills": ["Instrumentation", "Theory", "Stage Presence", "Songwriting"],
     "salary_range": "₹4-50 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Grade 4-6 formal exam."},
                 {"stage": "Grade 11-12", "action": "Grade 8 + audition."},
                 {"stage": "College", "action": "Music conservatory."},
                 {"stage": "Career", "action": "Session → Artist → Producer."}],
     "day_in_life": "Practice, rehearsals, gigs, songwriting."},
    {"career_id": "car_teacher", "name": "Teacher / Professor", "icon": "school", "color": "#059669",
     "tagline": "Multiply the future.",
     "description": "K-12 or university — teaching remains the most compounding career.",
     "top_colleges": ["Delhi University", "AMU", "IITs (for prof)"],
     "skills": ["Communication", "Patience", "Subject Depth"],
     "salary_range": "₹4-30 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Tutor a junior."},
                 {"stage": "Grade 11-12", "action": "TET awareness."},
                 {"stage": "College", "action": "Subject UG + B.Ed / PhD track."},
                 {"stage": "Career", "action": "Teacher → HoD → Principal / Prof."}],
     "day_in_life": "Classes, lesson planning, grading, mentoring."},
    {"career_id": "car_diplomat", "name": "Diplomat", "icon": "globe", "color": "#0284C7",
     "tagline": "Represent India to the world.",
     "description": "Foreign service — IFS through UPSC.",
     "top_colleges": ["Any UG + UPSC"],
     "skills": ["Languages", "Cultural Awareness", "Negotiation"],
     "salary_range": "₹10-30 LPA + postings",
     "roadmap": [{"stage": "Grade 9-10", "action": "Learn a foreign language."},
                 {"stage": "Grade 11-12", "action": "IR, world affairs reading."},
                 {"stage": "College", "action": "PolSci / History + UPSC prep."},
                 {"stage": "Career", "action": "IFS → Ambassador."}],
     "day_in_life": "Diplomatic cables, meetings, cultural events."},
    {"career_id": "car_filmmaker", "name": "Filmmaker / Director", "icon": "film", "color": "#7C2D12",
     "tagline": "Tell stories that move nations.",
     "description": "Direction, cinematography, screenwriting — cinema as vocation.",
     "top_colleges": ["FTII Pune", "SRFTI", "AFI Los Angeles"],
     "skills": ["Storytelling", "Visual Sense", "Leadership"],
     "salary_range": "₹5-100+ LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Shoot short films on phone."},
                 {"stage": "Grade 11-12", "action": "Film analysis, festival attendance."},
                 {"stage": "College", "action": "Film school + assistant on-set."},
                 {"stage": "Career", "action": "AD → Director → Producer."}],
     "day_in_life": "Script, storyboard, on-set, edit."},
    {"career_id": "car_astronaut", "name": "Astronaut / Space Engineer", "icon": "planet", "color": "#4C1D95",
     "tagline": "The final frontier.",
     "description": "ISRO, NASA, SpaceX — space is finally hiring at scale.",
     "top_colleges": ["IIST Trivandrum", "IIT Aerospace", "MIT AeroAstro"],
     "skills": ["Physics", "Fitness", "Nerves of Steel"],
     "salary_range": "₹12-80 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Astrophysics, astronomy club."},
                 {"stage": "Grade 11-12", "action": "IIST or IIT aerospace path."},
                 {"stage": "College", "action": "B.Tech Aerospace + ISRO internship."},
                 {"stage": "Career", "action": "Engineer → Mission specialist."}],
     "day_in_life": "Sim training, engineering reviews, physicals."},
    {"career_id": "car_chef", "name": "Chef", "icon": "restaurant", "color": "#F97316",
     "tagline": "Cook stories.",
     "description": "From Michelin star kitchens to your own cloud kitchen.",
     "top_colleges": ["IHM Delhi/Mumbai", "Le Cordon Bleu"],
     "skills": ["Palette", "Speed", "Stamina", "Business Sense"],
     "salary_range": "₹4-50 LPA",
     "roadmap": [{"stage": "Grade 9-10", "action": "Cook at home 3x/week."},
                 {"stage": "Grade 11-12", "action": "IHM entrance prep."},
                 {"stage": "College", "action": "B.Sc Culinary + kitchen internship."},
                 {"stage": "Career", "action": "Line cook → Sous → Head Chef."}],
     "day_in_life": "Prep, service, tasting menus, R&D."},
]


SEED_EVENTS = [
    {
        "event_id": "ev_mun_workshop", "title": "MUN Strategy Workshop", "kind": "workshops",
        "host": "Arjun Mehta", "host_avatar": "https://images.unsplash.com/photo-1544168190-79c17527004f?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-03-18", "time": "17:00", "duration": "90 min", "attendees": 124,
        "description": "Ace winning position papers and dominate committee.",
        "long_description": "Join Arjun (HMUN Finalist, 15+ MUN awards) for a hands-on 90-minute workshop covering: (1) how to write a winning position paper in 3 hours, (2) mid-committee negotiation tactics, (3) working paper strategy, (4) live Q&A with feedback on your own MUN videos.",
        "agenda": ["Position paper anatomy", "Bloc formation live drill", "Speech style workshop", "Q&A"],
        "location": "Online (Zoom)", "price": 0,
    },
    {
        "event_id": "ev_hackathon", "title": "48-hr High School Hackathon", "kind": "hackathons",
        "host": "Riya Gupta", "host_avatar": "https://images.unsplash.com/photo-1618355776464-8666794d2520?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1531545514256-b1400bc00f31?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-04-05", "time": "09:00", "duration": "48 hours", "attendees": 342,
        "description": "Build. Ship. Win ₹1L in prizes.",
        "long_description": "India's largest high-school-only hackathon. Solo or team of 4. Themes: EdTech, HealthTech, ClimateTech, AI-for-good. Prize pool: ₹1L. Mentors from IIT, Microsoft, Zomato.",
        "agenda": ["Kick-off & team formation", "Mentor office hours (24 slots)", "Midway checkpoint", "Final demo day"],
        "location": "Bangalore + Livestream", "price": 0,
    },
    {
        "event_id": "ev_debate_champ", "title": "National Debate Championship", "kind": "competitions",
        "host": "Ananya Jain", "host_avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-04-22", "time": "10:00", "duration": "2 days", "attendees": 96,
        "description": "Cambridge format. Top 16 schools invited.",
        "long_description": "The premier inter-school debate championship in India. 4 preliminary rounds, quarter-finals, semis, finals. Adjudicators from Cambridge Union & Oxford Union alumni network.",
        "agenda": ["Draw ceremony", "Rounds 1-4", "Quarter/Semi finals", "Grand finals + gala"],
        "location": "Delhi", "price": 500,
    },
    {
        "event_id": "ev_startup_bootcamp", "title": "Founder Bootcamp for Teens", "kind": "workshops",
        "host": "Kabir Rao", "host_avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1553877522-43269d4ea984?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-03-25", "time": "18:00", "duration": "3 sessions", "attendees": 210,
        "description": "Zero-to-one. Idea → MVP → first customer.",
        "long_description": "Three back-to-back sessions with Kabir Rao (Shark Tank India finalist). Session 1: idea validation. Session 2: ship a no-code MVP in 90 minutes. Session 3: getting your first 10 customers.",
        "agenda": ["Idea validation", "No-code MVP", "First 10 customers", "Live mentorship"],
        "location": "Online (Zoom)", "price": 199,
    },
    {
        "event_id": "ev_discussion_iit", "title": "IIT vs Ivy: Real Talk", "kind": "discussions",
        "host": "Advait Sharma", "host_avatar": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-03-15", "time": "20:00", "duration": "60 min", "attendees": 480,
        "description": "AMA with students who chose both paths.",
        "long_description": "Panel of 4 students who chose IIT vs Ivy League. Honest conversations about cost, culture, career, and homesickness. Open Q&A.",
        "agenda": ["Panel intros", "Comparison framework", "Q&A", "Networking"],
        "location": "Online", "price": 0,
    },
    {
        "event_id": "ev_design_circle", "title": "Design Circle: Portfolio Review", "kind": "workshops",
        "host": "Meera Iyer", "host_avatar": "https://images.unsplash.com/photo-1580489944761-15a19d654956?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1558655146-9f40138edfeb?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-04-02", "time": "17:30", "duration": "90 min", "attendees": 88,
        "description": "Live portfolio reviews for NID/UCEED aspirants.",
        "long_description": "Bring your design portfolio. Meera (NID Ahmedabad) will review 8 portfolios live and give actionable feedback. Others watch and learn.",
        "agenda": ["Portfolio submission", "Live reviews (8)", "Group critique"],
        "location": "Online", "price": 149,
    },
    # New events
    {
        "event_id": "ev_photo_walk", "title": "Photo Walk & Critique", "kind": "workshops",
        "host": "Zara Kapoor", "host_avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-03-29", "time": "07:00", "duration": "3 hours", "attendees": 42,
        "description": "Morning photo walk + live edit + critique.",
        "long_description": "Meet at 7 AM. Walk 3 KM through old Delhi lanes. Return, edit 3 favorites, get one-on-one critique from Zara. Bring any camera (phone works).",
        "agenda": ["Meet & warm-up", "Photo walk (3 KM)", "Edit session", "1:1 critique"],
        "location": "Old Delhi", "price": 299,
    },
    {
        "event_id": "ev_ai_workshop", "title": "Build Your First AI App", "kind": "workshops",
        "host": "Saanvi Rao", "host_avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1677442136019-21780ecad995?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-04-12", "time": "16:00", "duration": "2 hours", "attendees": 156,
        "description": "Ship a working AI app in 2 hours. No CS background required.",
        "long_description": "You will leave with a deployed AI-powered web app. We use Claude API + Streamlit. Bring a laptop. Requires no prior coding.",
        "agenda": ["Setup", "Prompt engineering basics", "Ship & deploy", "Q&A"],
        "location": "Online", "price": 0,
    },
    {
        "event_id": "ev_music_jam", "title": "Open Mic Music Jam", "kind": "competitions",
        "host": "Dev Malhotra", "host_avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-04-19", "time": "18:00", "duration": "3 hours", "attendees": 88,
        "description": "Perform. Get feedback. Meet fellow musicians.",
        "long_description": "Open mic night. 15-min slots (max 18). Solo or band. Judged by Dev Malhotra (Berklee) + audience. Winner gets a 3-hour recording session at a real studio.",
        "agenda": ["Sound check", "Performances", "Feedback panel", "Winner"],
        "location": "Mumbai", "price": 199,
    },
    {
        "event_id": "ev_chess_tourney", "title": "Rapid Chess Tournament", "kind": "competitions",
        "host": "Priya Nair", "host_avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1526401485004-2fda9f4f7ccc?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-04-14", "time": "10:00", "duration": "6 hours", "attendees": 64,
        "description": "10+0 rapid. Ratings 1000-2200. 7 rounds Swiss.",
        "long_description": "FIDE-rated event. Prize pool ₹25,000. Registration includes lunch. Boards, clocks, and scoresheets provided.",
        "agenda": ["Registration", "7 rounds", "Awards"],
        "location": "Bangalore", "price": 250,
    },
    {
        "event_id": "ev_public_speak", "title": "Public Speaking Bootcamp", "kind": "workshops",
        "host": "Naina Reddy", "host_avatar": "https://images.unsplash.com/photo-1499996860823-5214fcc65f8f?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-04-08", "time": "17:00", "duration": "2 hours", "attendees": 132,
        "description": "From shy to confident on stage in 2 hours.",
        "long_description": "Naina (TEDx Youth) shares her 3-step framework for overcoming stage fright. Includes live drills.",
        "agenda": ["Breathwork", "Impromptu drill", "Live speech", "Feedback"],
        "location": "Online", "price": 149,
    },
    {
        "event_id": "ev_lang_immersion", "title": "French Immersion Weekend", "kind": "workshops",
        "host": "Maria Fernandes", "host_avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-04-26", "time": "09:00", "duration": "2 days", "attendees": 28,
        "description": "48 hours of only-French. Start with basics, end with a play.",
        "long_description": "Full French immersion. No English allowed. Beginners welcome. Ends with a 15-min play performed in French.",
        "agenda": ["Basics", "Grammar drills", "Conversations", "Play"],
        "location": "Chennai", "price": 799,
    },
    {
        "event_id": "ev_study_group_boards", "title": "Boards Battle: Class 12 Study Group", "kind": "discussions",
        "host": "Advait Sharma", "host_avatar": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1509228468518-180dd4864904?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-03-20", "time": "20:00", "duration": "60 min", "attendees": 210,
        "description": "Weekly Class 12 board prep group. All streams welcome.",
        "long_description": "Recurring weekly session. Bring your doubts, get answers, share strategies. Focus rotates between Science, Commerce, Humanities.",
        "agenda": ["This week's topic", "Doubt round", "Study techniques", "Next week"],
        "location": "Online", "price": 0,
    },
    {
        "event_id": "ev_content_masterclass", "title": "Content Creator Masterclass", "kind": "workshops",
        "host": "Aryan Bhalla", "host_avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-04-10", "time": "18:00", "duration": "2 hours", "attendees": 320,
        "description": "How I grew 0-180K subs in 8 months.",
        "long_description": "Aryan reveals his exact playbook: niche selection, thumbnail design, hook writing, edit style, publishing rhythm. Includes free ChatGPT prompt pack.",
        "agenda": ["Niche selection", "Thumbnail A/B", "Editing style", "Monetization"],
        "location": "Online", "price": 249,
    },
]

SEED_REVIEWS = [
    {"mentor_id": "mnt_ananya", "user": "Kavya S.", "avatar": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80", "rating": 5, "text": "Ananya helped me win my first business quiz! Her frameworks are pure gold."},
    {"mentor_id": "mnt_ananya", "user": "Rohan M.", "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80", "rating": 5, "text": "The best mentor I've had. Made Business Studies feel intuitive."},
    {"mentor_id": "mnt_arjun", "user": "Ishita P.", "avatar": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80", "rating": 5, "text": "I won Best Delegate at my first MUN after 3 sessions with Arjun. Unreal."},
    {"mentor_id": "mnt_riya", "user": "Yash G.", "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80", "rating": 5, "text": "Riya's DSA sessions cleared 2 years of confusion. Now I'm addicted to Codeforces."},
    {"mentor_id": "mnt_advait", "user": "Aarohi K.", "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80", "rating": 5, "text": "From 60% to 94% in Physics in 3 months. Advait is a genius teacher."},
    {"mentor_id": "mnt_zara", "user": "Vikram R.", "avatar": "https://images.unsplash.com/photo-1544168190-79c17527004f?w=200&q=80", "rating": 5, "text": "Zara made me fall in love with photography again. Her compositions eye is incredible."},
    {"mentor_id": "mnt_saanvi", "user": "Anika D.", "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&q=80", "rating": 5, "text": "Cracked my first Kaggle competition after 4 sessions with Saanvi. She teaches like a friend."},
    {"mentor_id": "mnt_veer", "user": "Karan T.", "avatar": "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=200&q=80", "rating": 5, "text": "Veer's basketball drills gave me a 4-inch vertical improvement. Also great life advice."},
]
