"""Seed data for LEGACY app — mentors, vault resources, careers, events, reviews."""

SEED_MENTORS = [
    {
        "mentor_id": "mnt_ananya",
        "name": "Ananya Jain",
        "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "School Commerce Topper • Business Conclave Winner",
        "verified": True,
        "achievements": ["School Topper", "Business Conclave Winner", "Debate Finalist"],
        "subjects": ["Business Studies", "Economics", "Accountancy"],
        "categories": ["business", "academics", "debate"],
        "bio": "Passionate about business and finance. I love helping students build confidence and excel in competitions. I've won 4 national business conclaves and mentored 120+ juniors.",
        "rating": 4.9,
        "reviews_count": 126,
        "sessions": 128,
        "price": 299,
        "grade_taught": "Grade 9-12",
        "years": 2,
        "languages": ["English", "Hindi"],
        "available_slots": ["09:00", "10:00", "16:00", "17:00", "18:00"],
    },
    {
        "mentor_id": "mnt_arjun",
        "name": "Arjun Mehta",
        "avatar": "https://images.unsplash.com/photo-1544168190-79c17527004f?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1531545514256-b1400bc00f31?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "MUN Chair • Harvard Model UN Finalist",
        "verified": True,
        "achievements": ["Best Delegate x3", "HMUN Finalist", "Debate Captain"],
        "subjects": ["Political Science", "History", "Public Speaking"],
        "categories": ["mun", "debate", "public_speaking"],
        "bio": "MUN veteran with 15+ awards. I'll teach you how to research, negotiate, and dominate the committee floor.",
        "rating": 4.8,
        "reviews_count": 89,
        "sessions": 94,
        "price": 349,
        "grade_taught": "Grade 8-12",
        "years": 3,
        "languages": ["English"],
        "available_slots": ["10:00", "11:00", "17:00", "18:00", "19:00"],
    },
    {
        "mentor_id": "mnt_riya",
        "name": "Riya Gupta",
        "avatar": "https://images.unsplash.com/photo-1618355776464-8666794d2520?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1698434156107-17486c312c50?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "IIT Bombay CS • Coding Olympiad Gold",
        "verified": True,
        "achievements": ["IIT-B CSE", "IOI Bronze", "Google Code Jam"],
        "subjects": ["Python", "DSA", "Web Development"],
        "categories": ["coding", "ai", "academics"],
        "bio": "Full-stack developer & competitive programmer. Cracked JEE Advanced AIR 412. Let's build something amazing together.",
        "rating": 5.0,
        "reviews_count": 214,
        "sessions": 231,
        "price": 449,
        "grade_taught": "Grade 6-12",
        "years": 2,
        "languages": ["English", "Hindi"],
        "available_slots": ["16:00", "17:00", "18:00", "19:00", "20:00"],
    },
    {
        "mentor_id": "mnt_kabir",
        "name": "Kabir Rao",
        "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "Startup Founder • Shark Tank India Pitch Finalist",
        "verified": True,
        "achievements": ["Founder @18", "Shark Tank Finalist", "TIE Youth Winner"],
        "subjects": ["Entrepreneurship", "Product", "Pitching"],
        "categories": ["entrepreneurship", "business"],
        "bio": "Built a D2C brand in Class 12. I'll help you validate ideas, build MVPs, and pitch like a pro.",
        "rating": 4.9,
        "reviews_count": 67,
        "sessions": 72,
        "price": 499,
        "grade_taught": "Grade 9-12",
        "years": 1,
        "languages": ["English", "Hindi"],
        "available_slots": ["18:00", "19:00", "20:00"],
    },
    {
        "mentor_id": "mnt_meera",
        "name": "Meera Iyer",
        "avatar": "https://images.unsplash.com/photo-1580489944761-15a19d654956?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1509909756405-be0199881695?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "NID Ahmedabad • Design Thinking Coach",
        "verified": True,
        "achievements": ["NID Selected", "Adobe Design Winner"],
        "subjects": ["UI/UX", "Illustration", "Design Thinking"],
        "categories": ["design", "content"],
        "bio": "Cracked NID entrance in one attempt. I share the design portfolio & thinking process seniors wish they had.",
        "rating": 4.8,
        "reviews_count": 51,
        "sessions": 58,
        "price": 379,
        "grade_taught": "Grade 8-12",
        "years": 2,
        "languages": ["English", "Tamil"],
        "available_slots": ["11:00", "12:00", "17:00", "18:00"],
    },
    {
        "mentor_id": "mnt_advait",
        "name": "Advait Sharma",
        "avatar": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?crop=entropy&cs=srgb&fm=jpg&w=600&q=85",
        "cover": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "headline": "IMO Silver • Class XII Board Topper",
        "verified": True,
        "achievements": ["IMO Silver", "Board Topper 99.2%", "KVPY Fellow"],
        "subjects": ["Mathematics", "Physics", "JEE Prep"],
        "categories": ["academics", "olympiads"],
        "bio": "Cracked JEE Advanced AIR 89. Let's demystify calculus and physics from first principles.",
        "rating": 4.9,
        "reviews_count": 178,
        "sessions": 190,
        "price": 399,
        "grade_taught": "Grade 9-12",
        "years": 2,
        "languages": ["English", "Hindi"],
        "available_slots": ["17:00", "18:00", "19:00", "20:00"],
    },
]


SEED_VAULT = [
    {
        "vault_id": "v_business_conclave",
        "title": "Winning Business Conclave Presentation",
        "collection": "Winning Presentations",
        "category": "business",
        "author": "Ananya Jain",
        "author_avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 1240,
        "rating": 4.9,
        "year": "Class of 2024",
        "description": "The exact deck that won National Business Conclave 2024.",
    },
    {
        "vault_id": "v_debate_speech",
        "title": "National Debate Championship Speech",
        "collection": "Debate Speeches",
        "category": "debate",
        "author": "Arjun Mehta",
        "author_avatar": "https://images.unsplash.com/photo-1544168190-79c17527004f?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 890,
        "rating": 4.8,
        "year": "Class of 2023",
        "description": "8-minute finals speech — climate justice motion.",
    },
    {
        "vault_id": "v_mun_position",
        "title": "Harvard MUN Position Paper",
        "collection": "MUN Position Papers",
        "category": "mun",
        "author": "Advait Sharma",
        "author_avatar": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 1560,
        "rating": 5.0,
        "year": "Class of 2024",
        "description": "UNSC — Russia delegate. Best Position Paper award.",
    },
    {
        "vault_id": "v_pitch_deck",
        "title": "Shark Tank Style Pitch Deck",
        "collection": "Pitch Decks",
        "category": "entrepreneurship",
        "author": "Kabir Rao",
        "author_avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1553877522-43269d4ea984?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 2100,
        "rating": 4.9,
        "year": "Class of 2024",
        "description": "The 12-slide deck that got us to the finals.",
    },
    {
        "vault_id": "v_scholarship",
        "title": "Ivy League Scholarship Essay",
        "collection": "Scholarship Essays",
        "category": "academics",
        "author": "Riya Gupta",
        "author_avatar": "https://images.unsplash.com/photo-1618355776464-8666794d2520?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 3400,
        "rating": 5.0,
        "year": "Class of 2023",
        "description": "Full-ride to MIT. Read the essay + annotations.",
    },
    {
        "vault_id": "v_xii_notes",
        "title": "Class XII Physics Complete Notes",
        "collection": "Notes & Study Guides",
        "category": "academics",
        "author": "Advait Sharma",
        "author_avatar": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1509228468518-180dd4864904?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 5200,
        "rating": 4.9,
        "year": "Class of 2024",
        "description": "Hand-written, board-topper approved.",
    },
    {
        "vault_id": "v_case_study",
        "title": "Startup Case Study: 0 to 10Cr",
        "collection": "Pitch Decks",
        "category": "entrepreneurship",
        "author": "Kabir Rao",
        "author_avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 780,
        "rating": 4.7,
        "year": "Class of 2024",
        "description": "Full playbook — validation, MVP, GTM, first 100 users.",
    },
    {
        "vault_id": "v_design_portfolio",
        "title": "NID Design Portfolio 2024",
        "collection": "Winning Presentations",
        "category": "design",
        "author": "Meera Iyer",
        "author_avatar": "https://images.unsplash.com/photo-1580489944761-15a19d654956?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1558655146-9f40138edfeb?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 640,
        "rating": 4.9,
        "year": "Class of 2024",
        "description": "The portfolio that cracked NID Ahmedabad.",
    },
    {
        "vault_id": "v_debate_prep",
        "title": "Cambridge-Style Debate Prep Kit",
        "collection": "Debate Speeches",
        "category": "debate",
        "author": "Ananya Jain",
        "author_avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1544531586-fde5298cdd40?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "downloads": 420,
        "rating": 4.8,
        "year": "Class of 2024",
        "description": "Templates, rebuttal frameworks, timing drills.",
    },
]


SEED_CAREERS = [
    {
        "career_id": "car_marketing",
        "name": "Marketing",
        "icon": "trending-up",
        "color": "#F97316",
        "tagline": "Build brands. Shape culture.",
        "description": "Marketers understand people, craft campaigns, and drive growth.",
        "top_colleges": ["IIM Ahmedabad", "SP Jain", "NMIMS", "Wharton", "Kellogg"],
        "skills": ["Communication", "Creativity", "Analytics", "Storytelling"],
        "salary_range": "₹6-40 LPA",
        "roadmap": [
            {"stage": "Grade 9-10", "action": "Read Seth Godin, run a school Instagram."},
            {"stage": "Grade 11-12", "action": "Ace English & Business Studies. Try Coursera Digital Marketing."},
            {"stage": "College", "action": "BBA / BMS, then MBA in Marketing."},
            {"stage": "Career", "action": "Brand manager → CMO → Founder."},
        ],
        "day_in_life": "Standups, brand reviews, creative reviews, data dashboards, campaign approvals.",
    },
    {
        "career_id": "car_finance",
        "name": "Finance",
        "icon": "trending-up",
        "color": "#10B981",
        "tagline": "Master money. Move markets.",
        "description": "Finance runs the world. Learn how capital flows and value is created.",
        "top_colleges": ["SRCC", "St. Xavier's", "IIM", "LSE", "Wharton"],
        "skills": ["Excel", "Accounting", "Valuation", "Statistics"],
        "salary_range": "₹8-50 LPA",
        "roadmap": [
            {"stage": "Grade 9-10", "action": "Learn basic accounting, follow The Ken."},
            {"stage": "Grade 11-12", "action": "Take Commerce + Maths. Try CA Foundation."},
            {"stage": "College", "action": "B.Com, CFA Level 1, internships in IB."},
            {"stage": "Career", "action": "Analyst → VP → MD or Fund Manager."},
        ],
        "day_in_life": "Financial models, market news, client calls, pitch decks.",
    },
    {
        "career_id": "car_law",
        "name": "Law",
        "icon": "hammer",
        "color": "#2563EB",
        "tagline": "Argue with logic. Change society.",
        "description": "Law shapes democracy, business, and human rights.",
        "top_colleges": ["NLSIU Bangalore", "NALSAR", "NLU Delhi", "Harvard Law"],
        "skills": ["Reading", "Writing", "Debating", "Logical Reasoning"],
        "salary_range": "₹8-80 LPA",
        "roadmap": [
            {"stage": "Grade 9-10", "action": "Debate, MUN, read newspapers deeply."},
            {"stage": "Grade 11-12", "action": "Prep for CLAT. Join a mock CLAT program."},
            {"stage": "College", "action": "5-year BA LLB from NLU."},
            {"stage": "Career", "action": "Associate → Partner → Judge / Politician."},
        ],
        "day_in_life": "Case research, client meetings, drafting, courtroom, negotiations.",
    },
    {
        "career_id": "car_medicine",
        "name": "Medicine",
        "icon": "medkit",
        "color": "#EF4444",
        "tagline": "Heal. Discover. Serve.",
        "description": "Doctors save lives and push the frontier of human health.",
        "top_colleges": ["AIIMS", "CMC Vellore", "JIPMER", "Harvard Med"],
        "skills": ["Biology", "Empathy", "Precision", "Endurance"],
        "salary_range": "₹8-60 LPA",
        "roadmap": [
            {"stage": "Grade 9-10", "action": "Deep Biology + Chemistry. Shadow a doctor."},
            {"stage": "Grade 11-12", "action": "NEET prep. PCB core."},
            {"stage": "College", "action": "MBBS (5.5 yr) → MD/MS specialization."},
            {"stage": "Career", "action": "Resident → Consultant → Head of Dept."},
        ],
        "day_in_life": "OPD, rounds, surgeries, patient counseling, research.",
    },
    {
        "career_id": "car_engineering",
        "name": "Engineering",
        "icon": "construct",
        "color": "#8B5CF6",
        "tagline": "Build the future.",
        "description": "Engineers solve real-world problems with math, code, and grit.",
        "top_colleges": ["IIT Bombay/Delhi", "BITS Pilani", "IIIT-H", "MIT", "Stanford"],
        "skills": ["Math", "Physics", "Coding", "Problem Solving"],
        "salary_range": "₹10-80 LPA",
        "roadmap": [
            {"stage": "Grade 9-10", "action": "NTSE prep. Learn Python."},
            {"stage": "Grade 11-12", "action": "JEE Advanced / SAT. Build side projects."},
            {"stage": "College", "action": "B.Tech CS / EE / ME."},
            {"stage": "Career", "action": "SDE → Sr. Eng → Founder / CTO."},
        ],
        "day_in_life": "Standups, code reviews, design docs, shipping features.",
    },
    {
        "career_id": "car_design",
        "name": "Design",
        "icon": "color-palette",
        "color": "#EC4899",
        "tagline": "Where art meets impact.",
        "description": "Designers craft experiences that millions use every day.",
        "top_colleges": ["NID Ahmedabad", "IIT Bombay IDC", "RISD", "Parsons"],
        "skills": ["Sketching", "Empathy", "Figma", "Systems Thinking"],
        "salary_range": "₹6-60 LPA",
        "roadmap": [
            {"stage": "Grade 9-10", "action": "Sketch daily. Learn Figma."},
            {"stage": "Grade 11-12", "action": "Build a portfolio. Prep for NID/UCEED."},
            {"stage": "College", "action": "B.Des in Product / Communication."},
            {"stage": "Career", "action": "Designer → Lead → Head of Design."},
        ],
        "day_in_life": "Sketching, prototyping, user interviews, design critiques.",
    },
    {
        "career_id": "car_pilot",
        "name": "Pilot",
        "icon": "airplane",
        "color": "#0EA5E9",
        "tagline": "Own the skies.",
        "description": "Pilots operate one of the most complex machines ever built.",
        "top_colleges": ["IGRUA", "Bombay Flying Club", "CAE Oxford"],
        "skills": ["Physics", "Focus", "Decision Making", "Health"],
        "salary_range": "₹15-100 LPA",
        "roadmap": [
            {"stage": "Grade 9-10", "action": "PCM strong. Class 1 Medical."},
            {"stage": "Grade 11-12", "action": "12th PCM + DGCA prep."},
            {"stage": "College", "action": "CPL — 200 flying hours."},
            {"stage": "Career", "action": "First Officer → Captain → Chief Pilot."},
        ],
        "day_in_life": "Pre-flight checks, briefings, flying, layovers, ongoing training.",
    },
    {
        "career_id": "car_entrepreneur",
        "name": "Entrepreneurship",
        "icon": "rocket",
        "color": "#F59E0B",
        "tagline": "Build something that matters.",
        "description": "Entrepreneurs turn ideas into companies that shape the world.",
        "top_colleges": ["Not required — but Stanford, IIM, Wharton help."],
        "skills": ["Grit", "Sales", "Product Sense", "Fundraising"],
        "salary_range": "₹0 to ∞",
        "roadmap": [
            {"stage": "Grade 9-10", "action": "Sell something. Anything. Learn to code."},
            {"stage": "Grade 11-12", "action": "Ship a small product. Read Zero to One."},
            {"stage": "College", "action": "Build with co-founders. Apply to YC / Antler."},
            {"stage": "Career", "action": "Founder → Scale → Exit / IPO / Next venture."},
        ],
        "day_in_life": "Selling, hiring, fundraising, firefighting, occasional wins.",
    },
]


SEED_EVENTS = [
    {
        "event_id": "ev_mun_workshop",
        "title": "MUN Strategy Workshop",
        "kind": "workshops",
        "host": "Arjun Mehta",
        "host_avatar": "https://images.unsplash.com/photo-1544168190-79c17527004f?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-03-18",
        "time": "17:00",
        "duration": "90 min",
        "attendees": 124,
        "description": "Ace winning position papers and dominate committee.",
    },
    {
        "event_id": "ev_hackathon",
        "title": "48-hr High School Hackathon",
        "kind": "hackathons",
        "host": "Riya Gupta",
        "host_avatar": "https://images.unsplash.com/photo-1618355776464-8666794d2520?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1531545514256-b1400bc00f31?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-04-05",
        "time": "09:00",
        "duration": "48 hours",
        "attendees": 342,
        "description": "Build. Ship. Win ₹1L in prizes.",
    },
    {
        "event_id": "ev_debate_champ",
        "title": "National Debate Championship",
        "kind": "competitions",
        "host": "Ananya Jain",
        "host_avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-04-22",
        "time": "10:00",
        "duration": "2 days",
        "attendees": 96,
        "description": "Cambridge format. Top 16 schools invited.",
    },
    {
        "event_id": "ev_startup_bootcamp",
        "title": "Founder Bootcamp for Teens",
        "kind": "workshops",
        "host": "Kabir Rao",
        "host_avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1553877522-43269d4ea984?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-03-25",
        "time": "18:00",
        "duration": "3 sessions",
        "attendees": 210,
        "description": "Zero-to-one. Idea → MVP → first customer.",
    },
    {
        "event_id": "ev_discussion_iit",
        "title": "IIT vs Ivy: Real Talk",
        "kind": "discussions",
        "host": "Advait Sharma",
        "host_avatar": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-03-15",
        "time": "20:00",
        "duration": "60 min",
        "attendees": 480,
        "description": "AMA with students who chose both paths.",
    },
    {
        "event_id": "ev_design_circle",
        "title": "Design Circle: Portfolio Review",
        "kind": "workshops",
        "host": "Meera Iyer",
        "host_avatar": "https://images.unsplash.com/photo-1580489944761-15a19d654956?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1558655146-9f40138edfeb?crop=entropy&cs=srgb&fm=jpg&w=800&q=80",
        "date": "2026-04-02",
        "time": "17:30",
        "duration": "90 min",
        "attendees": 88,
        "description": "Live portfolio reviews for NID/UCEED aspirants.",
    },
]


SEED_REVIEWS = [
    {"mentor_id": "mnt_ananya", "user": "Kavya S.", "avatar": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80", "rating": 5, "text": "Ananya helped me win my first business quiz! Her frameworks are pure gold."},
    {"mentor_id": "mnt_ananya", "user": "Rohan M.", "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80", "rating": 5, "text": "The best mentor I've had. Made Business Studies feel intuitive."},
    {"mentor_id": "mnt_arjun", "user": "Ishita P.", "avatar": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80", "rating": 5, "text": "I won Best Delegate at my first MUN after 3 sessions with Arjun. Unreal."},
    {"mentor_id": "mnt_riya", "user": "Yash G.", "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80", "rating": 5, "text": "Riya's DSA sessions cleared 2 years of confusion. Now I'm addicted to Codeforces."},
    {"mentor_id": "mnt_advait", "user": "Aarohi K.", "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80", "rating": 5, "text": "From 60% to 94% in Physics in 3 months. Advait is a genius teacher."},
]
